Repository php-tuf/php-tuf, pull requests merged in 2020-08, with the labels that each got.

#32 Add typed exceptions based on #18
  src/Exception/FormatException.php
  src/Exception/NotFoundException.php
  src/Exception/PotentialAttackException/FreezeAttackException.php
  src/Exception/PotentialAttackException/PotentialAttackException.php
  src/Exception/PotentialAttackException/RollbackAttackException.php
  src/Exception/TufException.php
Labels: blocker

#31 Improve storage class naming and documentation
  src/Client/DurableStorage/DurableStorageAccessValidator.php
  src/Client/DurableStorage/FileStorage.php
  src/Client/DurableStorage/FilesystemDurableStorage.php
  src/Client/Updater.php
  tests/Client/UpdaterTest.php
  tests/DurableStorage/DurableStorageAccessValidatorTest.php
  tests/DurableStorage/MemoryStorage.php
Labels: blocker

#37 Add datetime conversion helper from #18
  src/Client/Updater.php
Labels: blocker

#39 Add missing phpdoc and typehints to the JsonNormalizer
  src/JsonNormalizer.php
Labels: coding standards, documentation

#41 Remove unneeded public and protected members from custom exception classes, and add docs and typehints
  src/Exception/FormatException.php
  src/Exception/NotFoundException.php
Labels: documentation

#26 Allow CI to pass when a line exceeds 120 characters (but still show the warning locally)
  .github/workflows/php.yml
  README.md
  composer.json
  phpcs-ci-ruleset.xml
Labels: coding standards

#43 Clean up KeyDBTest
  tests/KeyDBTest.php
Labels: coding standards, documentation

#34 Add array formatting rules and fix array indentation
  phpcs-ruleset.xml
  src/KeyDB.php
  tests/KeyDBTest.php
Labels: coding standards
