Repository php-tuf/php-tuf, pull requests merged in 2020-09, with the labels that each got.

#44 Copying docs for classes that were ported from Python TUF
  src/KeyDB.php
  src/RoleDB.php
Labels: documentation

#42 Add a custom phpcs rule to ensure code is documented
  PHP_CodeSniffer/Tuf/Sniffs/Commenting/FunctionCommentSniff.php
  PHP_CodeSniffer/Tuf/ruleset.xml
  phpcs-ci-ruleset.xml
  phpcs-ruleset.xml
Labels: coding standards, documentation

#18 Workflow steps 2.2, 2.3
  src/Client/Updater.php
  src/Exception/PotentialAttackException/SignatureThresholdExpception.php
  tests/Client/UpdaterTest.php
  tests/DurableStorage/DurableStorageAccessValidatorTest.php
  tests/TestHelpers/DurableStorage/MemoryStorage.php
  tests/TestHelpers/DurableStorage/MemoryStorageLoaderTrait.php
  tests/Unit/Client/UpdaterTest.php
Labels: needs test coverage
